version: 2.1
orbs:
  python: circleci/python@2.0.3

jobs:
  build:
    docker:
      - image: circleci/python:3.x
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy:
    executor: python/default
    machine:
      enabled: true
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Deploy via Systemd Service
          command: |
            sudo systemctl restart nuclei_backend.service
          background: true

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build # only deploy once build job has completed
          filters:
            branches:
              only: development # only deploy on the development branch
