version: "3"

volumes:
  data:

networks:
  my-network:
    driver: bridge

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql
    networks:
      - my-network
    restart: always

  redis:
    image: redis:latest
    volumes:
      - data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
      - target: 6379
    networks:
      - my-network
    restart: always
    privileged: true
    cap_add:
      - SYS_ADMIN

  nuclei_backend:
    image: ronnytec/nuclei:latest
    expose:
      - 8000
    ports:
      - 8000:8000
      - "8443:8000"
    environment:
      - "DATABASE_URL=postgresql://postgres:postgrespw@postgres:5432"
      - "REDIS_URL=redis://redis:6379"
    depends_on:
      - postgres
      - redis
    links:
      - postgres
      - redis
    restart: always
    volumes:
      - data:/app/data
    networks:
      - my-network
