version: "3"

volumes:
  data:

networks:
  traefik-network:
    external: true
  traefik-hub: {}
  mq-network:
    driver: bridge
  my-network:
    driver: bridge

services:

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql
    networks:
      - traefik-hub
      - my-network
    restart: always

  redis:
    image: redis:latest
    volumes:
      - data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
      - target: 6379
    networks:
      - traefik-hub
      - my-network
    restart: always
    privileged: true
    cap_add:
      - SYS_ADMIN

  hub-agent:
    image: ghcr.io/traefik/hub-agent-traefik:v1.1.0
    pull_policy: always
    container_name: hub-agent
    restart: "on-failure"
    
    command:
      - run
      - --hub.token=a1a13386-d01b-4465-aa68-3d492244649e
      - --auth-server.advertise-url=http://hub-agent
      - --traefik.host=traefik
      - --traefik.tls.insecure=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik-hub
    depends_on:
      - traefik

  traefik:
    image: traefik:v2.9
    container_name: traefik
    command:
      - --experimental.hub=true
      - --hub.tls.insecure=true
      - --metrics.prometheus.addrouterslabels=true
    networks:
      - traefik-hub

  nuclei_backend:
    build:
      context: .
      dockerfile: Dockerfile.app
    expose:
      - 8000
    ports:
      - 8000:8000
      - "8443:8000"
    environment:
      - "DATABASE_URL=postgresql://postgres:postgrespw@postgres:5432"
      - "REDIS_URL=redis://redis:6379"
    depends_on:
      - postgres
      - redis
    links:
      - postgres
      - redis
    restart: always
    volumes:
      - data:/app/data
    networks:
      - traefik-hub
      - my-network
