apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipfs-development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ipfs-development
  template:
    metadata:
      labels:
        app: ipfs-development
    spec:
      containers:
        - name: ipfs
          image: ipfs/kubo:latest
          ports:
            - containerPort: 4001
              protocol: TCP
            - containerPort: 4001
              protocol: UDP
            - containerPort: 5001
            - containerPort: 8081
          restartPolicy: UnlessStopped
